# — — — — —  — — — — — — — — — — — — — — — — — — #
#                   First Query                  
# — — — — —  — — — — — — — — — — — — — — — — — — #

[[Query]]
CsvPath = "./data/itemResults.csv"
HdrNames = []
IncCol = false
Name = "Query 1"
OutCsv = "./out/itemResults_out.csv"
RelaOfCond = "&"

[[Query.Cond]]
Header = "School"
RelaOfCellValue = "="
Value = "21221"
ValueType = "string"

# — — — — —  — — — — — — — — — — — — — — — — — — #
#                   Second Query                  
# — — — — —  — — — — — — — — — — — — — — — — — — #

[[Query]]
CsvPath = "./data/itemResults999.csv"
HdrNames = ["School", "Item Response"]
IncCol = false
Name = "Query 2"
OutCsv = "./out/itemResults999_out.csv"
RelaOfCond = "&"

[[Query.Cond]]
Header = "Domain"
RelaOfCellValue = "!="
Value = "Reading"
ValueType = "string"

[[Query.Cond]]
Header = "YrLevel"
RelaOfCellValue = "<"
Value = 9
ValueType = "int"
